name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.0
          terraform_wrapper: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Run Renovate
        run: npx --yes renovate@43.213.3
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_CLI_ARGS_init: -backend=false
          RENOVATE_ALLOWED_COMMANDS: '["^terraform init -upgrade -backend=false$", "^terraform providers lock -platform=linux_amd64 -platform=linux_arm64 -platform=darwin_arm64$"]'
